// JavaScript Document
var RainbowSnowflakeSettings = function() {
	ctx.globalCompositeOperation = "source-over";
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(0.6);
	$("#alpha_value_slider").slider('value',0.6);
	$("#line_width").val(2);
	$("#line_width_slider").slider('value',2);
	$("#shadow_color").val('#ffffff');
	$("#shadow_blur").val(12);
	$("#shadow_blur_slider").slider('value',12);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = true;
	document.getElementById("mode").value = 3;
	document.getElementById("geo_mode").value = 4;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}
var WhiteSnowflakeSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(0.6);
	$("#alpha_value_slider").slider('value',0.6);
	$("#line_width").val(2);
	$("#line_width_slider").slider('value',2);
	$("#shadow_color").val('#ffffff');
	$("#shadow_blur").val(12);
	$("#shadow_blur_slider").slider('value',12);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = true;
	document.getElementById("mode").value = 3;
	document.getElementById("geo_mode").value = 4;
	$('#cp1').val("#FFFFFF");
	$('#cp2').val("#FFFFFF");
	$('#cp3').val("#FFFFFF");
	$('#cp4').val("#FFFFFF");
	$('#cp5').val("#FFFFFF");
	$('#cp6').val("#FFFFFF");
	$('#cp7').val("#FFFFFF");
	$('#cp8').val("#FFFFFF");
	$('#cp9').val("#FFFFFF");
	$('#cp10').val("#FFFFFF");
	$('#cp11').val("#FFFFFF");
	$('#cp12').val("#FFFFFF");
	$('#cp13').val("#FFFFFF");
}
var FractalTreeSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#max_branch_level").val(8);
	$("#max_branch_level_slider").slider('value',8);
	$("#branch_length").val(2000);
	$("#branch_length_reduction").val(98);
	$("#branch_angle").val(20);
	$("#branch_angle_slider").slider('value',20);
	$("#branch_thickness").val(0.6);
	$("#branch_thickness_reduction").val(66);
	$("#numbranches").val(2);
	document.getElementById("add_random_range").checked = false;
	document.getElementById("add_shadow").checked = false;
	document.getElementById("random_color_order").checked = false;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = true;
	document.getElementById("mode").value = 0;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#331100");
	$('#cp2').val("#851607");
	$('#cp3').val("#d11919");
	$('#cp4').val("#a83605");
	$('#cp5').val("#a82e27");
	$('#cp6').val("#ba5a02");
	$('#cp7').val("#cf4253");
	$('#cp8').val("#998417");
	$('#cp9').val("#d6a831");
	$('#cp10').val("#ffc700");
	$('#cp11').val("#9bfa00");
	$('#cp12').val("#00ff7f");
	$('#cp13').val("#ff8800");
}

var ArteriesSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#shadow_color").val('#ff0000');
	$("#shadow_blur").val(12);
	$("#shadow_blur_slider").slider('value',12);
	$("#max_branch_level").val(12);
	$("#max_branch_level_slider").slider('value',12);
	$("#branch_length").val(1000);
	$("#branch_length_reduction").val(84);
	$("#branch_angle").val(15);
	$("#branch_angle_slider").slider('value',15);
	$("#branch_thickness").val(0.5);
	$("#branch_thickness_reduction").val(76);
	$("#numbranches").val(1);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = true;
	document.getElementById("add_leaves").checked = false;
	document.getElementById("mode").value = 0;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#FF0000");
	$('#cp2').val("#FF0000");
	$('#cp3').val("#FF0000");
	$('#cp4').val("#FF0000");
	$('#cp5').val("#FF0000");
	$('#cp6').val("#FF0000");
	$('#cp7').val("#FF0000");
	$('#cp8').val("#FF0000");
	$('#cp9').val("#FF0000");
	$('#cp10').val("#FF0000");
	$('#cp11').val("#FF0000");
	$('#cp12').val("#FF0000");
	$('#cp13').val("#FF0000");
}

var PeterMaxSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(0.6);
	$("#alpha_value_slider").slider('value',0.6);
	$("#shadow_color").val('#000000');
	$("#shadow_blur").val(50);
	$("#shadow_blur_slider").slider('value',50);
	$("#max_branch_level").val(8);
	$("#max_branch_level_slider").slider('value',8);
	$("#branch_length").val(1000);
	$("#branch_length_slider").slider('value',1000);
	$("#branch_length_reduction").val(125);
	$("#branch_length_reduction_slider").slider('value',125);
	$("#branch_angle").val(45);
	$("#branch_angle_slider").slider('value',45);
	$("#branch_thickness").val(0.8);
	$("#branch_thickness_slider").slider('value',0.8);
	$("#branch_thickness_reduction").val(125);
	$("#branch_thickness_reduction_slider").slider('value',125);
	$("#numbranches").val(2);
	$("#numbranches_slider").slider('value',2);
	document.getElementById("add_random_range").checked = true;
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = true;
	document.getElementById("mode").value = 0;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var ChakraSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#alpha_value").val(0.4);
	$("#alpha_value_slider").slider('value',0.4);
	$("#max_branch_level").val(10);
	$("#max_branch_level_slider").slider('value',10);
	$("#branch_length").val(775);
	$("#branch_length_slider").slider('value',775);
	$("#branch_length_reduction").val(98);
	$("#branch_length_reduction_slider").slider('value',98);
	$("#branch_angle").val(30);
	$("#branch_angle_slider").slider('value',30);
	$("#branch_thickness").val(0.4);
	$("#branch_thickness_slider").slider('value',0.4);
	$("#branch_thickness_reduction").val(66);
	$("#branch_thickness_reduction_slider").slider('value',66);
	$("#numbranches").val(2);
	$("#numbranches_slider").slider('value',2);
	document.getElementById("add_shadow").checked = false;
	document.getElementById("add_random_range").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = false;
	document.getElementById("mode").value = 0;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var SpaceFernsSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#shadow_color").val('#FFFFFF');
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#random_range").val(10);
	$("#random_range_slider").slider('value',12);
	$("#shadow_blur").val(15);
	$("#shadow_blur_slider").slider('value',15);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("single_random_factor").checked = false;
	document.getElementById("add_random_range").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("mode").value = 2;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var SierpinskiGasketSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#shadow_color").val('#FFFFFF');
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#shadow_blur").val(15);
	$("#shadow_blur_slider").slider('value',15);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("single_random_factor").checked = false;
	document.getElementById("add_random_range").checked = false;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("mode").value = 1;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var BarnsleyFernSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#shadow_color").val('#FFFFFF');
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#shadow_blur").val(15);
	$("#shadow_blur_slider").slider('value',15);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("single_random_factor").checked = false;
	document.getElementById("add_random_range").checked = false;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("mode").value = 2;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var CharcoalSketchSettings = function() {
	$("#root_node_scale").val(1);
	$("#root_node_scale_slider").slider('value',1);
	$("#line_width").val(3);
	$("#line_width_slider").slider('value',3);
	$("#alpha_value").val(0.1);
	$("#alpha_value_slider").slider('value',0.1);
	$("#branch_length").val(2);
	$("#branch_length_slider").slider('value',2);
	$("#spline_curvature").val(-2);
	$("#spline_curvature_slider").slider('value',-2);
	$("#spline_curvature_random_factor").val(10);
	$("#spline_curvature_random_factor_slider").slider('value',10);
	$("#shadow_color").val('#FFFFFF');
	$("#shadow_blur").val(5);
	$("#shadow_blur_slider").slider('value',5);
	$("#shadow_offset").val(5);
	$("#shadow_offset_slider").slider('value',5);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = false;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = false;
	document.getElementById("mode").value = 3;
	document.getElementById("geo_mode").value = 9;
	$('#cp1').val("#FFFFFF");
	$('#cp2').val("#FFFFFF");
	$('#cp3').val("#FFFFFF");
	$('#cp4').val("#FFFFFF");
	$('#cp5').val("#FFFFFF");
	$('#cp6').val("#FFFFFF");
	$('#cp7').val("#FFFFFF");
	$('#cp8').val("#FFFFFF");
	$('#cp9').val("#FFFFFF");
	$('#cp10').val("#FFFFFF");
	$('#cp11').val("#FFFFFF");
	$('#cp12').val("#FFFFFF");
	$('#cp13').val("#FFFFFF");
}

var WormLinesSettings = function() {
	$("#line_width").val(10);
	$("#line_width_slider").slider('value',10);
	$("#alpha_value").val(0.01);
	$("#alpha_value_slider").slider('value',0.01);
	$("#root_node_scale").val(8);
	$("#root_node_scale_slider").slider('value',8);
	$("#shadow_color").val('#FFFFFF');
	$("#shadow_blur").val(8);
	$("#shadow_blur_slider").slider('value',8);
	document.getElementById("add_shadow").checked = true;
	document.getElementById("random_color_order").checked = true;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = false;
	document.getElementById("mode").value = 3;
	document.getElementById("geo_mode").value = 7;
	$('#cp1').val("#aa00aa");
	$('#cp2').val("#ff00ff");
	$('#cp3').val("#8800ff");
	$('#cp4').val("#0000ff");
	$('#cp5').val("#0088ff");
	$('#cp6').val("#00ffff");
	$('#cp7').val("#00ff88");
	$('#cp8').val("#00ff00");
	$('#cp9').val("#88ff00");
	$('#cp10').val("#ffff00");
	$('#cp11').val("#ff8800");
	$('#cp12').val("#ff0000");
	$('#cp13').val("#990000");
}

var SimplePathSettings = function() {
	ctx.globalCompositeOperation = "source-over";
	$("#line_width").val(5);
	$("#line_width_slider").slider('value',5);
	$("#alpha_value").val(1);
	$("#alpha_value_slider").slider('value',1);
	$("#shadow_color").val('#FFFFFF');
	$("#shadow_blur").val(8);
	$("#shadow_blur_slider").slider('value',8);
	document.getElementById("add_shadow").checked = false;
	document.getElementById("random_color_order").checked = false;
	document.getElementById("random_branch_length").checked = false;
	document.getElementById("add_leaves").checked = false;
	document.getElementById("mode").value = 3;
	document.getElementById("geo_mode").value = 0;
	$('#cp1').val("#FFFFFF");
	$('#cp2').val("#FFFFFF");
	$('#cp3').val("#FFFFFF");
	$('#cp4').val("#FFFFFF");
	$('#cp5').val("#FFFFFF");
	$('#cp6').val("#FFFFFF");
	$('#cp7').val("#FFFFFF");
	$('#cp8').val("#FFFFFF");
	$('#cp9').val("#FFFFFF");
	$('#cp10').val("#FFFFFF");
	$('#cp11').val("#FFFFFF");
	$('#cp12').val("#FFFFFF");
	$('#cp13').val("#FFFFFF");
}
